--dropEmpTables.sql
--Name: Marissa Gonçalves
--Date: October 25, 2018


DROP TABLE emplevel CASCADE CONSTRAINTS;
DROP TABLE position CASCADE CONSTRAINTS;
DROP TABLE qualification CASCADE CONSTRAINTS;
DROP TABLE dept CASCADE CONSTRAINTS;
DROP TABLE employee CASCADE CONSTRAINTS;
DROP TABLE dependent CASCADE CONSTRAINTS;
